#Drag For JoyStick------------------------------------------------------------
<DragJS>:
    #Define the properties for the DragJS
    size_hint:None,None
    drag_rectangle: self.x, self.y, self.width, self.height
    drag_timeout: 10000000
    drag_distance: 0
#End--------------------------------------------------------------------------

#Image With Rotation and Movement----------------------------------------------
<RO@Widget>:
    angle:0
    pos:100,100
    #size_hint:None,None
    source:""
    ratio:False
    Image:
        source:root.source
        allow_stretch:True
        keep_ratio:root.ratio
        size:root.size
        pos:(root.center[0] - self.size[0]/2,root.center[1] - self.size[1]/2)
        canvas.before:
            PushMatrix
            Rotate:
                angle: root.angle
                origin: self.center
        canvas.after:
            PopMatrix
#End--------------------------------------------------------------------------

#Joy Stick Back---------------------------------------------------------------
<JS0@Widget>:
    size_hint:None,None
    color1:(1,1,0,1)
    #size:(100,100)
    pos:(0,0)
   
<Joystick0@JS0>:
    canvas.before:
        Color:
            rgba: root.color1
        Ellipse:
            pos: root.pos
            size: root.size
#End--------------------------------------------------------------------------

#Energy Bar-------------------------------------------------------------------
<EB@Widget>:
    s1:""
    s2:""
    size_hint:None,None
    s1size:(100,100)
    s1pos:(100,100)
    Image:
        source:root.s2
        allow_stretch:True
        keep_ratio:False
        size:root.size
        pos:root.pos
    Image:
        source:root.s1
        allow_stretch:True
        keep_ratio:False
        size:root.s1size
        pos:root.s1pos
#End--------------------------------------------------------------------------

#Main
<RMassets>:
    Widget:
        id:FB
        size_hint:None,None
        size: root.size
        RO:
            id:A1
            angle:0
            size_hint:None,None
            ratio:True
            pos:root.size[0]/2 - self.size[0]/2,root.size[1]/2 - self.size[1]/2
            size:root.size[0]/12,root.size[0]/12
            source:"./Ship/1.png"
    Widget:
        size_hint:None,None
        size: root.size
        FloatLayout:
            EB:
                id:energy_bar
                s1:"./HUD/EnergieBarColor2.png"
                s2:"./HUD/EnergieBar2.png"
                size: root.size[0]/5, root.size[1]/20
                pos:(0,root.size[1]-self.size[1])
                s1size:(self.size[0]*22)/25,(self.size[1]*3)/5
                s1pos:self.pos[0] + (self.s1size[0]*1.69)/25, self.pos[1] + (self.s1size[1]*1.665)/5
            Button:
                text: "Fire"
                pos: root.size[0]*6/8,root.size[1]/6
                size_hint:None,None
                size:root.size[0]/8,root.size[0]/8
                on_press: root.startfire()
                on_release: root.stopfire()

            Joystick0:
                id:B1
                pos:root.size[0]/8,root.size[1]/6#Set Joy Stick Pos
                size:root.size[0]/8,root.size[0]/8
                
            DragJS:
                id:B2
                size:B1.size[0]/2, B1.size[1]/2
                pos:B1.pos[0] + B1.size[0]/2 - B1.size[0]/4, B1.pos[1] + B1.size[1]/2 - B1.size[1]/4
                color:(1,0,0,1)
                canvas:
                    Color:
                        rgba:self.color
                    Ellipse:
                        size:self.size
                        pos:self.pos
                #on_touch_down:root.doit()
            
<Menu>:
    Widget:
    Image:
        id:BI
        source:"./Background/1.png"
        size:root.size
        allow_stretch:True
        keep_ratio:False
        pos:(0,0)
    BoxLayout:
        orientation:"horizontal"
        BoxLayout:
            orientation:"vertical"
            Label:
                text:"LOGO"
                
            Button:
                text:"Bullets"
                size_hint:(1,0.5)
                on_press:root.manager.current = 'S_G'
            Button:
                text:"Ships"
                size_hint:(1,0.5)
                on_press:root.manager.current = 'S_S'
            Button:
                text:"Stats"
                size_hint:(1,0.5)
                on_press:root.manager.current = 'STAT'
            Button:
                text:"Settings"
                size_hint:(1,0.5)
                on_press:root.manager.current = 'S_'
            Label:
                text:"LOGO"
                
        BoxLayout:
            orientation:"vertical"
            Label:
                text:"Space Shooter"
                size_hint:(1,0.5)
            RO:
                id:A11
                angle:0
                pos:root.size[0]/2 - self.size[0]/2,root.size[1]/2 - self.size[1]/2
                ratio:True
                source:"./Ship/1.png"
            BoxLayout:
                id:Bullet_Stat
                orientation:"horizontal"
                size_hint:(1,0.5)
                Label:
                    text:"Bullet"
                Widget:
                    id:t123
                    Image:
                        id:BSImg
                        source:"./Shoot/1.png"
                        allow_stretch:True
                        pos:t123.center[0] - self.size[0]/2, t123.center[1] - self.size[1]/2
                        keep_ratio:True
                        size:t123.size[0]/3,t123.size[1]/3
        BoxLayout:
            orientation:"vertical"
            Label:
                text:"LOGO"
                
            Button:
                text:"Game Mode"
                size_hint:(1,0.5)
                on_press:root.manager.current = 'G_M'
            Button:
                text:"Club"
                size_hint:(1,0.5)
                on_press:root.manager.current = 'C_B'
            Button:
                text:"Friends"
                size_hint:(1,0.5)
                on_press:root.manager.current = 'F_S'
            Button:
                text:"History"
                size_hint:(1,0.5)
                on_press:root.manager.current = 'HIS'
            Label:
                text:"LOGO"
                size_hint:(1,0.5)
            Button:
                text:"Start"
                size_hint:(1,0.5)
                on_press: root.manager.current = 'P_G_'

<Select_Gun>:
    Label:
        id: L_
        text: "Select Gun"
        size_hint: (0.9, 0.1)
        pos: (0,root.size[1]-self.size[1])
    Button:
        text:"<-"
        size_hint: (None,0.1)
        pos: (root.size[0] - self.size[0], root.size[1]-self.size[1])
        on_press: root.manager.current = 'M_'

    BoxLayout:
        orientation: "horizontal"
        size_hint: None, None
        size: (root.size[0], root.size[1]-L_.size[1])
        ScrollView:
            id: SV1
            do_scroll_x: False
            do_scroll_y: True
                
        Button:
            on_press: root.doit()
    
                

<Select_Ship>:
    Label:
        id: SS_
        text: "Select Ship"
        size_hint: (0.9, 0.1)
        pos: (0,root.size[1]-self.size[1])
    Button:
        text:"<-"
        size_hint: (None,0.1)
        pos: (root.size[0] - self.size[0], root.size[1]-self.size[1])
        on_press: root.manager.current = 'M_'

    BoxLayout:
        orientation: "horizontal"
        size_hint: None, None
        size: (root.size[0], root.size[1]-SS_.size[1])
        ScrollView:
            id: SV2
            do_scroll_x: False
            do_scroll_y: True
                
        Button:
            on_press: root.doit()

<Game_Over>:

<About>:

<Stats>:

<Settings>:

